apiVersion: v1
kind: Secret
metadata:
  name: argocd-openbao-env
  namespace: argocd
data:
  AVP_AUTH_TYPE: dG9rZW4=
  AVP_TYPE: dmF1bHQ=
  AVP_SKIP_TLS_VERIFY: dHJ1ZQ==
  VAULT_ADDR: aHR0cDovL29wZW5iYW8ub3BlbmJhby5zdmM6ODIwMA==
  VAULT_TOKEN: cm9vdA==
type: Opaque
